# Generated by Django 3.1.5 on 2021-01-07 06:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coinrate',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 7, 6, 51, 21, 241352, tzinfo=utc)),
        ),
    ]
